### ISSUE TITLE
README is very out of date

### ISSUE THREAD

**Issue by mxgrey** [open-rmf/rmf_traffic#9]
We should wipe the README of this repo clean and have it focus more directly on `rmf_traffic` instead of being about RMF broadly.

We should also update the README of https://github.com/osrf/rmf_core to redirect users towards https://github.com/open-rmf/rmf

**Comment by gbiggs** [comment]
Updating the old repository READMEs is on my list as soon as we finish the final repository's migration.

I'm probably not the right person to write a README for `rmf_traffic`, though. I will say that I think the content of the README should be the same as the front page of the package's documentation at open-rmf.readthedocs.io.

**Comment by mxgrey** [comment]
Would it be feasible/desirable for the front page `readthedocs` documentation for this package to simply display the README contents?

**Comment by gbiggs** [comment]
I believe that it is possible, because the README location is fixed relative to the documentation source location.
